### PR TITLE
Calc parse type

### PR DESCRIPTION
**Pull request by jaybekster**
Tried to solve problem for that issue: https://github.com/ben-eb/cssnano/issues/296
But there is still one problem, that string:
`linear-gradient(to left bottom, transparent calc(50% - 2px), #a7a7a8 0, #a7a7a8 calc(50% + 2px), transparent 0)`
transforms into: 
`linear-gradient(to right bottom,transparent calc(50% - 2px),#a7a7a8 0,#a7a7a8 calc(50% + 2px),transparent)`

I can't see where I can fix it exactly in your module, so that it would be great if you look at this.

### CODE REVIEW

**Comment by ben-eb** [comment]
Hello @jaybekster, thanks for your contribution! 🎉 

Could you add a test case for the failure please? 😄

**Comment by jaybekster** [comment]
Here you are

**Comment by ben-eb** [comment]
Thanks! I'm a bit confused by your original post though, does this patch fix your issue with cssnano? It looks like it does to me, would you care to elaborate? Thanks again. 😄

**Comment by jaybekster** [comment]
Yes, it fixed my problem.
When I found a problem in my transformed css, I decided to create an issue in cssnano without deep understanding the problem. After sometime, I went deeper in that problem I realized that the problem is in `postcss-minify-gradients` package, that cssnano is dependable on. And now I fixed it! :)

**Comment by ben-eb** [comment]
Thanks! Released in 1.0.4. 😄

**Pull request merged**
